### ISSUE TITLE
export tile map

### ISSUE THREAD

**Issue by ordos31** [ComputerNerd/Retro-Graphics-Toolkit#4]
Hi,
is it possible to export the tile map in the Format of the used color patette? The Images are always saved in 24 bit rgb Format (png, bmp). But if  I import an image based on the genesis palette with 16 Colors (4 bit indexed Color) in the way:

File -> Tile Map -> Import Images to Tile Map 
Patete Actions -> Generate optimal Palette.. -> dont Change Anything ..
Tile Map Actions -> Toggle True Color Viewing) 24 bit are not nessesary.   

the additional Tile Map Export supports  only 24 bit rgb mode (png, bmp). Is it possible to Export images in 4 bit indexed Color mode, when 16 Colors are used?

The advantage is you can direct import the Images in sgdk and draw with the optimal color palette.

Maybe ist's easy for you to implement this.

**Comment by ComputerNerd** [comment]
> 24 bit are not necessary
The original 32bit tiles are stored in ram because the user may want to change the palette later on. This allows the user to simply dither the tiles again to fit the new palette.

> the additional Tile Map Export supports only 24 bit rgb mode
I agree the Tile Map Export should generate an index image. I know that tiles are 4-bit but Retro Graphics Toolkit may end up generating a 8-bit image if more than one row are used. Just keep that in mind. I can make Retro Graphics Toolkit check if only one row is used and if so generate a 4-bit image or otherwise generate an 8-bit image. This is easy to implement.

**Comment by ComputerNerd** [comment]
I have implemented 8-bit png exporting in commit b9b5983fbc4c3767ee8cf1c44ad732acc866a8db. If you are using the windows binary you can either compile it or wait for the next release or run pngout on the images and it will convert it to an 8-bit image. The reason I did not bother checking for 4-bit images is because I recall sgdk having trouble with 4-bit images. This was a few years ago and may not be the case. I am leaving this issue in case it turns out that it can now handle 4-bit images and I should implement that.

**Comment by ComputerNerd** [comment]
I forgot to mention that I released Retro Graphics Toolkit v0.8 awhile ago and it contains support for exporting 8-bit pngs. This was done in commit 54c8b5afb83737bae01dbcf40be467898ae32799

**Comment by ordos31** [comment]
Thank you for implement the 8-bit png format. Now i can Import the Images in sgdk direct and they look better than images converted with gimp.
